src/objects/College__c.object
<CustomObject>
    <label>College</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <referenceTo>College__c</referenceTo>
        <relationshipLabel>Teachers</relationshipLabel>
        <relationshipName>Teachers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QueryParentToChild.cls
public with sharing class QueryParentToChild {
    public void OpportunityAccount(){
        for(Account account :[select Name,(select Name from Opportunities)from Account]){
            System.debug('Account :' +account.Name);
            for(Opportunity opp :account.Opportunities){
                System.debug('Opportunty :'+opp.Name);
            }
        }
    }
    public void CollegeTeacher(){
        for(College__c college : [Select Name, (Select Name from Teachers__r) from College__c]){
            System.debug('College Name : '+college.Name);
            for(Teacher__c teacher : college.Teachers__r){
                System.debug('Teacher Name : '+teacher.Name);
            }
        }
    }
}